### ISSUE TITLE
DB labels mangled

### ISSUE THREAD

**Issue by jrgreen7** [rdnelson/Libra#112]
It appears that variable names (labels) used with SOME DB commands are mangled in the source window. Is there a way to fix this? 

It looks like DB commands that allocate a string may be an issue. DB directives that only allocate/initialize an int look ok...

**Comment by rdnelson** [comment]
Did you use the timer.OBJ provided, or did you use some other code? If it was other code, could you post it here so I can duplicate the bug?

**Comment by jrgreen7** [comment]
Hi Robert,

I've seen it in two of my OBJ files. Attached one here. MESSAGE1 is 
mangled...

Cheers,
Jim.

On 21/03/2013 11:30 AM, Robert Nelson wrote:

> Did you use the timer.OBJ provided, or did you use some other code? If 
> it was other code, could you post it here so I can duplicate the bug?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/rdnelson/Libra/issues/112#issuecomment-15245372.

## 

James Green, PhD, P.Eng.
Associate Professor
Systems & Computer Engineering
Carleton University, Ottawa, Canada
http://www.sce.carleton.ca/faculty/green
