### ISSUE TITLE
Would prefer lst view of code showing hex values for instructions/DBs

### ISSUE THREAD

**Issue by jrgreen7** [rdnelson/Libra#113]
Is it possible to show the machine code corresponding to each line of code, similar to the .lst file? Would help students understand what is being highlighted in the memory contents window...

**Comment by rdnelson** [comment]
Would you like the machine code to be included in the instruction list, or continue to be a separate file?

**Comment by jrgreen7** [comment]
I think I'd like the instruction list to have the machine code on the 
left, like a LST file.

If this was a toggleable view setting, even better!

Thanks,
Jim.

On 21/03/2013 11:27 AM, Robert Nelson wrote:

> Would you like the machine code to be included in the instruction 
> list, or continue to be a separate file?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/rdnelson/Libra/issues/113#issuecomment-15245205.

## 

James Green, PhD, P.Eng.
Associate Professor
Systems & Computer Engineering
Carleton University, Ottawa, Canada
http://www.sce.carleton.ca/faculty/green

**Comment by rdnelson** [comment]
Ok, that's perfectly do-able. It'll be in next week's release.

**Comment by DarrenStahl** [comment]
Issue addressed by #132 

Commenting to link issue to solution

@rdnelson are you going to merge the fix into gui? I've done more testing, and it looks all good.
