### ISSUE TITLE
Toolbar icons missing

### ISSUE THREAD

**Issue by jrgreen7** [rdnelson/Libra#114]
My toolbar has buttons, but they are invisible...

**Comment by rdnelson** [comment]
This sounds like a glitch with the deployment steps, they were written yesterday, so I'll investigate.

**Comment by rdnelson** [comment]
Fix has been submitted, just need further testing on a different dev box to ensure dynamic builds weren't broken. 
@DarrenStahl could you pull the beta-1.2-vs2010-redist branch and ensure that you can still build the 'release' and 'debug' configurations. 'release_static' shouldn't work for you though.

**Comment by DarrenStahl** [comment]
@rdnelson dynamic builds confirmed to work on both my dev boxes.

**Comment by rdnelson** [comment]
Great, I'm going to push a static debug version in a few minutes and then close the issue. Thanks for the confirmation.

**Comment by rdnelson** [comment]
Ok, the new commit is up. @DarrenStahl any chance for another check?

**Comment by DarrenStahl** [comment]
All is good still. Want me to build Qt statically to test the static builds on a different dev box as well?

**Comment by rdnelson** [comment]
I've covered testing the two static builds. When I built Qt in static mode I found that it messes up the dynamic libraries, preventing me from compiling them again. Otherwise I would have tested those myself. Thanks for the verification, I'm going to merge the branch and resolve this Issue now.
