### ISSUE TITLE
JE rel8 jumps to the wrong location

### ISSUE THREAD

**Issue by DarrenStahl** [rdnelson/Libra#120]
Steps to reproduce:
1. Load lab41b.OBJ (provided by email)
2. Step through program
3. Observe the JE after printing the string jumps the IP to 0x0025 rather than 0x1025

Notes: Looking at the addresses it seems rather obvious that the top byte of the IP is being ignored in rel8 jumps. Should be an easy fix.

**Comment by rdnelson** [comment]
Fixed by #123. Commenting for link.
