### ISSUE TITLE
Screen scrolling 

### ISSUE THREAD

**Issue by DarrenStahl** [rdnelson/Libra#124]
See attached screenshot:

![Screen_Scroll_bug](https://f.cloud.github.com/assets/2420691/295032/aac10da2-9443-11e2-98c4-f8eeb0b528ea.png)
Left side of the screenshot is while screen is scrolling. Right side is the same program before screen scroll starts.

**Comment by rdnelson** [comment]
@DarrenStahl Could you check out the screen_scroll branch and see if that resolves the issue?

**Comment by DarrenStahl** [comment]
Issue is not solved, it appears that some of the line leaving the top of the screen reappears at the bottom unless overwritten.

screen_scrolling also does not appear to trigger both newline and carriage return as it attempts to. Only the CR is getting through.

**Comment by rdnelson** [comment]
You're right it doesn't seem to work. The fix was based on me forgetting how everything hooked together. I've found the real problem (I think, but I still need to fix the Return needing to send both 0x0A and 0x0D.) There should be a new fix in 15 minutes or so.

**Comment by DarrenStahl** [comment]
I have a fix for sending both CR and LF, pushing to git now.

**Comment by DarrenStahl** [comment]
Only problem is, that since some of the labs are built on waiting for a key to be pressed, and enter now "presses" two keys, the prompt will be printed twice. We should confirm expectations on this one, as some labs may need tweaking.

**Comment by rdnelson** [comment]
Has the code been pushed somewhere yet?

**Comment by rdnelson** [comment]
What do the labs expect in terms of enter being pressed?

**Comment by DarrenStahl** [comment]
As far as I can tell, Virgo only sends 0x0A, and interprets that at screen output as a CR+LF. This fix doesn't break any labs, just prompts twice on enter.

**Comment by rdnelson** [comment]
I think there's probably a better way of handling this. The two keypress solution that we've both submitted changes for   is an unrealistic way of fixing this problem. The real way it should be fixed is in the assembly code running. It should look for an 0x0A being fed by the keyboard, and then write both 0x0A and 0x0D to the screen. That's the way windows does it.

The other solution is to simply change Libra to use Linux line endings. This will only require 0x0A to be printed to the screen, and it will register an entire NL+CR sequence.

The second solution is probably better, because otherwise there's an inconsistency in the way the keyboard keys are handled.

Thoughts?

**Comment by DarrenStahl** [comment]
I think the Linux line endings are a better option, but, is it best to teach students Linux line endings when most will be (primarily) working on Windows?

**Comment by rdnelson** [comment]
I just looked through the Virgo code. It seems that they do what we have now. 0x0A increments the screen's Y coordinate, and 0x0D sets the x Coordinate to 0. That's probably the best way to deal with this. Just forget about changing the keyboard, and I'll just submit the real fix to this bug.

**Comment by rdnelson** [comment]
Check screen_scroll2 for a fix?

**Comment by DarrenStahl** [comment]
Original bug is fixed, but feeding enter key presses directly to the screen only does a NL, and not a CR.

**Comment by rdnelson** [comment]
That's all it's supposed to do, and all Virgo did.

**Comment by rdnelson** [comment]
As this bug doesn't deal with the keyboard CR-LF issue, I'm going to create an enhancement bug for that, and move this discussion there. I'm going to merge the fix for this issue in, and close.
