### ISSUE TITLE
Request for notification on encountering HLT

### ISSUE THREAD

**Issue by hasithvm** [rdnelson/Libra#125]
When the halt machine instruction (0xF4) is encountered, the application should notify the user that the execution has halted. Preferably done as a popup window or output to stdio.

**Steps to reproduce:**
1. Load executable Virgo object file into simulator.
2. Clicked run
3. No feedback application has finished execution, other than output to (internal) terminal.

While the documented behavior for HLT on x86 is to deep idle the processor until an external interrupt is received, Libra should still notify the user that the simulator has entered said state.

**Comment by rdnelson** [comment]
There are currently two separate behaviours that HLT has. The first is if IF is clear, this is the case where execution stops, and a message box should be shown. The second is if IF is set, where displaying a message box will block the GUI thread and interfere with interrupt execution. In the second case, execution is continuing, so no message box will be shown.

**Comment by hasithvm** [comment]
I'm assuming IF refers to the Instruction Flag checkbox. Has the behavior above been implemented already? If so, it did not trigger for me when I ran both a known p86asm54-generated file, and a p86-ng generated object file,

**Comment by rdnelson** [comment]
Yes IF is the Interrupt Flag, and the message box is not yet there, although the other behaviour described is. This is a valid issue, and I'll have a fix in about half an hour.
