### ISSUE TITLE
Keyboard should trigger both CR and LF on Return keypress

### ISSUE THREAD

**Issue by rdnelson** [rdnelson/Libra#131]
This issue opens the issue of whether the keyboard should trigger both a CR + LF when the return key is pressed, or whether it should just duplicate Virgo (and real computer's) behaviour of just returning LF (0x0A).

**Comment by DarrenStahl** [comment]
I had thought that Virgo did both at screen print, after testing it, yes it only returns a LF, and the programmer must ad a CR. 

I agree that we should emulate Virgo's behavior, but ask Dr. Green if this is what he would like (since we have fixes for all combinations available).

**Comment by rdnelson** [comment]
Ok, this will be an action point for beta 1.4, pending a final decision from Dr. Green. It will be added to the beta 1.3 release notes.
