### ISSUE TITLE
When HLT is reached and execution stops, next instruction is highlighted.

### ISSUE THREAD

**Issue by rdnelson** [rdnelson/Libra#138]
Steps to reproduce:
1. Load a file that has no interrupts and ends in HLT
2. Run program until HLT is reached

This is a discussion that needs to be raised. In this case, should the next instruction be highlighted. Technically the IP has already moved on to that instruction before the HLT was executed, so it makes sense. On the other hand, it's confusing that it looks like the program is ending on the next, (or no) instruction.

@hasithvm, @DarrenStahl Thoughts?

**Comment by DarrenStahl** [comment]
I'm on the same thoughts as you. The IP HAS moved on, and it could be used to explain that the processor will continue to try to read "instructions" from memory, even if there are no instructions left, unless it is stopped.

At the same time, I see it could be confusing to everyone who is new to assembly.

Overall, I have a slight preference toward highlighting the next "instruction", but think this should be Dr. Green's decision, as he is the one that will have to explain about the instruction memory model.

**Comment by rdnelson** [comment]
I think for now, I'll leave the current behaviour there. It spawns an interesting discussion, and means that we don't need to make a change.

Closing unless this is reopened by Dr. Green.
