### ISSUE TITLE
Add right-click on instruction listing to set breakpoint

### ISSUE THREAD

**Issue by hasithvm** [rdnelson/Libra#144]
This is the way NoICE does it, and it's an intuitive enhancement. Rather than selecting an instruction in the listing and doing the menu dance, it's far more intuitive to simply right-click->Set Breakpoint, or something similar. 

_Possible Issues_
1. Differentiating between data and instructions. 
2. ...

Any thoughts? @DarrenStahl @rdnelson

**Comment by rdnelson** [comment]
I agree. This is still an immature feature, along with the lack of conditional breakpoints and watches. I'll start working on these this weekend.

As for the issues, I don't see a problem setting a breakpoint on data, because it'll never get hit, but IP could potentially be set to it.
