### ISSUE TITLE
Step Into/Over does not function as expected when HLT is encountered

### ISSUE THREAD

**Issue by hasithvm** [rdnelson/Libra#145]
When using step into/over to debug , the step into/over buttons do not trigger expected functionality when HLT is executed.

**Expected**
When stepping into/over a HLT instruction, the message box indicating HLT status should trigger if the IF is not set.

**Observed**
No message box indicating HLT has been reached, instruction highlighting disappears.

**Comment by rdnelson** [comment]
This issue is indicative of another, which is that stepping currently runs in the GUI thread. This needs to be fixed, because if a step out takes a long time, then the GUI locks up until (hopefully) it finishes.

**Comment by hasithvm** [comment]
Is this tied into higher-than-expected CPU usage at idle? top says libra-qt idles at 6-7% CPU usage.

**Comment by rdnelson** [comment]
No, it isn't, I've opened issue #146 for that.
