### ISSUE TITLE
loop doesn't work.

### ISSUE THREAD

**Issue by kevincox** [rdnelson/Libra#182]
Using the latest git (513a214a340fd85033a218d475fe39e1d79ef820) the loop instruction doesn't work.

``` asm
Start:
    mov CX, 8
    ALoop:
        inc AX ; Only gets run once!
        loop ALoop ; Doesn't loop!

    hlt

.END Start
```

When running this code the loop never gets taken even though `CX` is 8.

**Comment by rdnelson** [comment]
The current HEAD has a fix for this. Can you confirm it works?

**Comment by kevincox** [comment]
Yes, it works.

Cheers.
