### ISSUE TITLE
[BP+SI] and [BP+DI] cannot be used for based register indirect addressing. 

### ISSUE THREAD

**Issue by MichaelDysart** [rdnelson/Libra#198]
The registers [BP+SI] and [BP+DI] should be acceptable for based register indirect addressing mode. 

However, using them in an instructions (for example, mov CX, [BX + SI]) produces an undefined label assembly error.

I have attached a .txt file with the code that generates the error. 

[BasedIndexingModeError.txt](https://github.com/rdnelson/Libra/files/525167/BasedIndexingModeError.txt)

**Comment by rdnelson** [comment]
Is this a assembly time error?

**Comment by MichaelDysart** [comment]
Yes

**Comment by rdnelson** [comment]
The assembler is actually hosted in a different project at https://github.com/hasithvm/lasm Can you file the issue there?

**Comment by MichaelDysart** [comment]
My mistake. I will re-submit the error. Sorry for the inconvenience.

**Comment by rdnelson** [comment]
No worries, it's nice to see people still filing bugs!
