### ISSUE TITLE
Screen doesn't update on Win32 sometimes.

### ISSUE THREAD

**Issue by rdnelson** [rdnelson/Libra#93]
Steps to reproduce:
1. Load timer.OBJ
2. Run program

Expected Results:
Screen should fill with periods.

Actual Results:
Screen stays blank.

Additional information:
If the procedure is replaced with:
1. Load timer.OBJ
2. Step through program until the line out [dx], al is highlighted.
3. Step once more.
4. Run the program

The screen updates, but the display is not updated regularly. Periods will appear in groups, but the correct number of them seem to appear.

**Comment by rdnelson** [comment]
I believe that this is actually two different issues. The issue where the screen doesn't update is caused by the improper use of QTimer which is the heart of the Timer peripheral. I don't think that the screen update rate issue is related to this. I suggest refining this issue to just deal with the screen update rate problem, and opening a new issue for the QTimer issue.

**Comment by DarrenStahl** [comment]
I am unable to reproduce the lack of screen updates as described. I do see the screen updating in clusters, and will revise my debugging to deal with that issue, and attempt to reproduce the blank screen on other systems.

**Comment by rdnelson** [comment]
Reopening for windows performance updates.

**Comment by rdnelson** [comment]
Screen updates no longer an issue.
